### ISSUE TITLE
Custom event trigger doesn't work on... custom events

### ISSUE THREAD

**Issue by Chaphasilor** [justintaddei/vue-haptic#2] opened 2020-10-03 20:46 UTC
I'm trying to trigger haptics on a certain, custom event (created using `$emit(`failed`)` inside `CustomElement`).  
However, when I try to use
```vue
<CustomElement
  v-haptic:error="{
    trigger: `failed`,
  }"
>
```
nothing happens when the event is emitted.  
I have an event listener (`@failed`) set up which confirms that the event is actually emitted.

I thought this was meant by *custom events* in the docs?  
If not, is there a way to achieve this?

**Comment by Chaphasilor** [comment] 2020-10-03 21:33
I created a basic Sandbox for demonstration: https://codesandbox.io/s/dazzling-williamson-oow06

You'll notice that the behavior is really strange, with the `failed` pattern being used every time, regardless of the event being emitted.  
In general I found that only the last v-haptic directive will be used (try putting `v-haptic:failed` above the normal `v-haptic`, you'll get the default pattern).

**Comment by justintaddei** [comment] 2020-10-05 03:04
That would be because I used `addEventListener` to listen for DOM events instead of listening for a Vue event.  I'll look into a way to make it work for either one!

**Comment by Chaphasilor** [comment] 2020-10-05 09:05
Nice.

I think Vue event support is vitally important for this!

**Comment by justintaddei** [comment] 2020-10-05 13:07
I 100% agree. I'm a little swamped right now but I'll have time to work on this in about 2 days.

**Comment by Chaphasilor** [comment] 2020-10-05 13:26
Take your time!

But I'll be sure to remind you 😈

**Comment by justintaddei** [comment] 2020-10-09 01:19
A fix has been implemented! I just need to reword the docs a bit and then I'll publish a new minor release.

Modifiers now support setting the trigger to **any** event! Before, you could only set it so one of the following:  

- `v-haptic.click`
- `v-haptic.pointerup`
- `v-haptic.pointerdown`
- `v-haptic.change`
- `v-haptic.input`

Now you could do this:
```vue
<CustomElement
  v-haptic:error.failed
>

<!-- or -->

<CustomElement
  v-haptic:error="{
    trigger: `failed`,
  }"
>
```

**Comment by justintaddei** [comment] 2020-10-09 02:44
vue-haptic@1.1.0 has been released! Enjoy!

**Comment by Chaphasilor** [comment] 2020-10-09 11:11
Awesome! Let me check it out real quick!

**Comment by Chaphasilor** [comment] 2020-10-09 13:02
Okay, so the event listening does work as expected. Great job!

However, I'm struggling again with #1 (kinda).

Specifically, I have a toggle, and I want a short vibration when I click it (or on the `input` event, boils down to the same), and a double vibration on the `failed` event.
So, I click the toggle to enable a setting, but if the setting can't be enabled (e.g. permission denied by the user, internal error, you name it), the toggle switches back to the disabled state, the `failed`-event is emitted and a double vibration should occur.

However, this doesn't seem possible.

```vue
<BasicToggle
    @input="$emit(`change`, $event)"
    @failed="log"
    v-haptic="{
      trigger: `input`,
    }"
    v-haptic:error="{
      trigger: `failed`,
    }"
/>
``` 
This outputs the `error` pattern on *every* event, so on click/`input` and also on `failed`.

```vue
<BasicToggle
    @input="$emit(`change`, $event)"
    @failed="log"
    v-haptic
    v-haptic:error="{
      trigger: `failed`,
    }"
/>
``` 
This has no vibration on click/input, but the `error` pattern on `failed`.

```vue
<BasicToggle
    @input="$emit(`change`, $event)"
    @failed="log"
    v-haptic
/>
``` 
This causes no vibration at all for some reason? Setting `v-haptic` inside the outermost div in the `BasicToggle` component works however.

```vue
<BasicToggle
    @input="$emit(`change`, $event)"
    @failed="log"
    v-haptic:error="{
      trigger: `failed`,
    }"
/>

<-- BasicToggle.vue -->
<template>
<div
  class="..."
  v-haptic
>
...
</div>
</template>
```
This causes a single vibration on both click/`input` as well as `error`.

So I have two questions:
1. Why is `v-haptic` on my `BasicToggle` not working, only inside the definition?
2. Why can't I specify different vibration patterns based on different events?

I've set up a test branch for you at https://github.com/Chaphasilor/njoy-frontend/tree/haptics.
The relevant components are `SettingsItem` and `BasicToggle`, the settings page has two toggles, one that will never fail (*Test Setting*) and one that *should* always fail (if it prompts for notification permission, block it).

**Comment by justintaddei** [comment] 2020-10-09 15:51
Ah. I think I know why that's happening even without testing anything.

I'm using a `WeakMap` with the element as the key and the pattern as the value so that I can update it when the detective's value changes; essentially acting as a global store. The problem is all of that happens without regard for the event used. If I rewrite it to store the patterned based the element **and** the event, it should work.

I'll see how that works.

**Comment by Chaphasilor** [comment] 2020-10-09 15:58
Great! Yeah, sometimes debugging is easy xD

**Comment by justintaddei** [comment] 2020-10-11 05:28
And then again sometimes debugging it's so easy. I'm trying to come up with a way to support both DOM and Vue events with a single listener because apparently $on() doesn't emit regular DOM events. I always thought it did...

Any ideas?

**Comment by Chaphasilor** [comment] 2020-10-11 09:22
I can't even find proper documentation for `vm.$on()`...

So no, no idea how to do this. But I don't think it's necessary at all? Why not just register two event handlers? Or maybe you can you the `.native` modifier for this somehow?

**Comment by justintaddei** [comment] 2020-10-11 14:40
Hm. I suppose listening for both wouldn't be an issue. For some reason I had it in my mind that it would cause weird overlap issues with doubled up events but that doesn't appear to be the case.

**Comment by justintaddei** [comment] 2020-10-15 05:07
A fix for this is coming soon (hopefully tomorrow). I've been trying to figure out a long term solution to this because Vue 3 has removed `vm.$on`. 

I've been discussing this with several individuals on the Vue discord and have been told there is no migration strategy. Ideally I would like to avoid hooking into undocumented behavior to listen to custom events. Tomorrow I plan to go over the Vue 3 source add see how the new event system is implemented.

I'll keep you updated of my discoveries.

This seemed so simple in the beginning :)

**Closed** 2020-10-15 19:22 UTC
Labels: bug

**Comment by Chaphasilor** [comment] 2020-10-15 19:29
Okay, so what did you change now? Only the data structures? 🤔 

I'll try it out sometime tomorrow :)

**Comment by justintaddei** [comment] 2020-10-15 19:46
Before, it would register the handler using `Element.addEventListener` if it was on a _native element_ and use `vm.$on` if it was on a _component_. Now, it will always register the event with `Element.addEventListener` and if it's on a component, it will also register the handler with `vm.$on`. I was worried that would cause the handler to be invoked twice in some cases, but as it turns out, even if it is `navigator.vibrate` will just cancel the first invocation. Easy!

To address the issue of it only using the last pattern, I changed the data structure from a 1D `Map<Element, Pattern>` to a 2D `Map<Element, Map<Trigger, Pattern>>`.

These changes were just released as vue-haptic@1.1.1

**Comment by Chaphasilor** [comment] 2020-10-20 15:39
Ayyy, it's working 🥳  
(Sorry that this took me so long 😅)

Thanks a ton! If you're bored at some point you might wanna add support for using the dot notation with custom events...
See the second example [here](https://www.npmjs.com/package/vue-haptic#usage):
> Use with a different trigger event: `v-haptic.pointerup`

Currently, `v-haptic.failed:error` doesn't work, whereas `v-haptic:error="{trigger: `failed`}"` does work just fine :)
You might also wanna clarify this in the readme until it's working...

Also, thanks for the explanation of your changes :D

Another thing I noticed, on the first touch/click event that triggers v-haptic, I get the following error in the console:
```
[Intervention] Blocked call to navigator.vibrate because user hasn't tapped on the frame or any embedded frame yet: https://www.chromestatus.com/feature/5644273861001216.
vibrate @ index.esm.js?5bd9:73
eval @ index.esm.js?5bd9:78
```
The error is pretty clear to me, I'm just wondering if this could be prevented (because it also prevents the first vibration after page load from firing). My guess is this has something to do with the way vue directives are executed? Not sure though...

I have yet another problem, but I'll open another issue for that xD

**Comment by justintaddei** [comment] 2020-10-20 15:51
> Currently, v-haptic.failed:error doesn't work

Does `v-haptic:error.failed` work? I don't think it's valid syntax to have the modifier before the argument.

> `[Intervention] Blocked call to navigator.vibrate because user hasn't tapped on the frame or any embedded frame yet: https://www.chromestatus.com/feature/5644273861001216.
vibrate @ index.esm.js?5bd9:73
eval @ index.esm.js?5bd9:78`

This is similar to how the WebAudio API works where you have to interact with the page before the page is allowed to play a sound. As long the first element the user interacts with is a non-haptic one, the error shouldn't appear. Also, if the trigger event is set to `click` instead of `pointerdown` it would likely prevent this as well. I'm going to leave it as `pointerdown` since the error doesn't really hurt anything and using `click` can make the app feel slow (if feels delayed compared to native haptic implementations).

**Comment by Chaphasilor** [comment] 2020-10-20 16:00
> Does `v-haptic:error.failed` work? I don't think it's valid syntax to have the modifier before the argument.

That actually does work! I would've thought *that* would be invalid syntax, oh well xD

> > `[Intervention] Blocked call to navigator.vibrate because user hasn't tapped on the frame or any embedded frame yet: https://www.chromestatus.com/feature/5644273861001216. vibrate @ index.esm.js?5bd9:73 eval @ index.esm.js?5bd9:78`
> 
> This is similar to how the WebAudio API works where you have to interact with the page before the page is allowed to play a sound. As long the first element the user interacts with is a non-haptic one, the error shouldn't appear. Also, if the trigger event is set to `click` instead of `pointerdown` it would likely prevent this as well. I'm going to leave it as `pointerdown` since the error doesn't really hurt anything and using `click` can make the app feel slow (if feels delayed compared to native haptic implementations).

Yeah, that's what I thought. And there's really no way to use click instead? I'm having issues with `pointerdown` triggering when scrolling a list of elements which are clickable, but it shouldn't vibrate on scroll. Using `click` fixes that, but as you said it's delayed (although I think that is due to v-shared-element, get ready for my issue there xD).  
Click normally is a really solid event for properly triggering actions only when something is pressed, I've found no better event that won't fire on other occasions as well so far...

**Comment by justintaddei** [comment] 2020-10-20 16:07
> That actually does work! I would've thought that would be invalid syntax, oh well xD

Do you mean that the both syntaxes are valid or that changing the order fixed the issue?


> I'm having issues with pointerdown triggering when scrolling a list of elements which are clickable, but it shouldn't vibrate on scroll.

There may be a way I can use `pointercancel` detect when the event triggered while scrolling. I've been experimenting with that already for `v-wave`. If I find a solution I'll port to here as well!

**Comment by Chaphasilor** [comment] 2020-10-20 20:13
> Just make sure your modifiers are after the argument: [Vue.js directive docs](https://vuejs.org/v2/guide/custom-directive.html#Directive-Hook-Arguments)

Yeah, I just thought that v-haptic.<onThisEvent>:<vibrateLikeThis> made more sense, so I messed up the syntax. Not your mistake though :)

> There may be a way I can use `pointercancel` detect when the event triggered while scrolling. I've been experimenting with that already for `v-wave`. If I find a solution I'll port that over here as well!

That sounds good. `click` is a bad fix, really (although it *should* be good), so fixing the unwanted scroll trigger on your end would be better for now 😅
